name: CommonsBase_Remote@0.1.x
on:
  push:
    tags:
      - '0.1.*'
  workflow_dispatch:

jobs:
  distribute:
    environment: dk-distribution
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      attestations: write
      artifact-metadata: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176
        with: { egress-policy: audit }

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Distribute Modules
        uses: diskuv/dk-distribute@v3
        with:
            pubkey: ${{ secrets.distribute_0_1_pubkey }}
            seckey: ${{ secrets.distribute_0_1_seckey }}
            options: -nosysinc
            store: release
            standalone: true
            distscript: dist/any.u
            execution-abi: Linux_x86_64
            target-abi: Linux_x86_64
            experimental-mlfront-ref: ${{ github.ref_type != 'tag' && 'HEAD' }}

      - name: Attest
        id: attest
        uses: actions/attest-build-provenance@v3
        with: { subject-path: dk-dist/* }

      - name: Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe
        with: { files: dk-dist/*, body_path: ".dist-CHANGELOG.txt" }
